### ISSUE TITLE
Revisión del punto 6 de la documentación y discusión de nuevos escenarios

### ISSUE THREAD

**Issue by Verdejo55** [Arquisoft/viade_es1b#12]
Revisar el diagrama y la explicación del mismo que esta en la rama feature_06runtime_view. Propuestas de nuevos escenarios por ejemplo como agregar una ruta al mapa? O dejarlo para mas adelante cuando tengamos mas claro como lo vamos hacer? Yo propongo hacer un mini esquema en el que pongas como va a interaccionar la aplicación para tener mas o menos un guía

**Comment by ricopozasmarcial** [comment]
Bueno como bien dices podemos hacer uno a modo de prototipo con los elementos esenciales y ya en un futuro cuando tengamos más experiencia podemos refirnarlo

**Comment by Verdejo55** [comment]
Pues voy hacer el diagrama de como añadir una ruta?

**Comment by Verdejo55** [comment]
La doy por cerrada al añadir un escenario mas, proximamente se abrira otra para debatir sobre otros escenarios
