### ISSUE TITLE
Añadir más requisitos si se os ocurre alguno mas y comprobar si alguno esta donde debería estar

### ISSUE THREAD

**Issue by Verdejo55** [Arquisoft/viade_es1b#3]
He añadido algún requisito que veía importante y los he separado en funcionales y no funcionales. Si veis que alguno esta donde no debe estar cambiarlo sin problema y si veis alguno que falta añadirlo también sin problema. Si no veis ninguno cerrar la issue.

**Comment by Mario-Miguel** [comment]
He retocado algunos de los requisitos que creía que estaban mal redactados. Los que hay creo que están bien.
