### ISSUE TITLE
Hacer frontend de la página del mapa

### ISSUE THREAD

**Issue by Mario-Miguel** [Arquisoft/viade_es1b#37]
El mapa ya se muestra, ahora deberiamos ponerlo guapo

**Comment by ricopozasmarcial** [comment]
Vale me pongo a ello

**Comment by ricopozasmarcial** [comment]
He ajustado para que se pueda ver a tamaño completo el mapa en función del dispositivo. Intento embellecer algo mas

**Comment by ricopozasmarcial** [comment]
He acabado el primer prototipo con selección de rutas en local
