### ISSUE TITLE
Eliminar opciones por defecto de la app

### ISSUE THREAD

**Issue by ricopozasmarcial** [Arquisoft/viade_es1b#39]
Estoy viendo si sería necesario eliminar las demás opciones de la aplicación por defecto y dejar lo que nos sirve

**Comment by uo265135** [comment]
No es mala idea, mejor no tener cosas de más. Me pongo con ello cuando pueda si no estas ya con eso.

**Comment by ricopozasmarcial** [comment]
No hay problema ya estoy yo en ello

**Comment by Verdejo55** [comment]
He visto que este punto esta cerrado y comprobado de que no salgan opciones predefinidas que no necesitamos
