### ISSUE TITLE
Hay que actualizar el dev con el contenido del master al haber mergeado ayer la documentación 03 en el master y no en el dev.

### ISSUE THREAD

**Issue by UO245110** [Arquisoft/viade_es1b#6]
Ayer sin querer acepté el pull request sin fijarme la rama de destino. ¿Alguien podría actualizar la rama developer con el contenido del master? (Debería estar la documentación 03)

**Comment by Mario-Miguel** [comment]
Ya está solucionado, haced pull de master y dev y listo
