### ISSUE TITLE
Desplegar aplicación en Docker

### ISSUE THREAD

**Issue by Mario-Miguel** [Arquisoft/viade_es1b#75]
Deberiamos empaquetar y probar a desplegar nuestra aplicación en docker

**Comment by Mario-Miguel** [comment]
He estado buscando como configurar el fichero Dockerfile y se crea laimagen de la aplicación. Todavía no soy capaz de hacer elcompose con el servidor de solid

**Comment by Mario-Miguel** [comment]
Ahora el compose se ejecuta parcialmente bien. Se crean ambas imágenes, la del servidor de solid y la de la aplicación, pero la de la aplicación no se ejecuta automaticamente

**Comment by UO245110** [comment]
Hemos descubierto que poniendo esta línea de código

stdin_open: true

¡Funciona!
